export type AttributionConfidence = "High" | "Medium" | "Low"

export interface AttributionRow {
  id: string
  channel: string
  spend: number
  // Revenue across measurement sources
  platformReported: number // e.g., Meta or Google reported
  ga4: number
  shopifyFirstClick: number
  shopifyLastClick: number
  postPurchaseSurvey: number
  blendedTruth: number // Optilytics blended
  // Derived
  blendedRoas: number
  contributionMargin: number
  confidence: AttributionConfidence
  flag?: "double_count_risk" | "uplift_unconfirmed" | "view_through_dependent"
  notes: string
}

export const attributionRows: AttributionRow[] = [
  {
    id: "meta-ads",
    channel: "Meta Ads",
    spend: 12400,
    platformReported: 64200,
    ga4: 38800,
    shopifyFirstClick: 32400,
    shopifyLastClick: 28600,
    postPurchaseSurvey: 41200,
    blendedTruth: 39800,
    blendedRoas: 3.21,
    contributionMargin: 11200,
    confidence: "High",
    notes:
      "Platform-reported revenue is 61% higher than the Shopify Blended view, mostly from view-through credit. We weight click-based and survey signals.",
  },
  {
    id: "google-search",
    channel: "Google Search",
    spend: 7800,
    platformReported: 31200,
    ga4: 28600,
    shopifyFirstClick: 21400,
    shopifyLastClick: 27800,
    postPurchaseSurvey: 18400,
    blendedTruth: 24600,
    blendedRoas: 3.15,
    contributionMargin: 6840,
    confidence: "High",
    notes:
      "Closest alignment across sources. Last-click bias is moderate; survey suggests some demand is partially captured by other channels.",
  },
  {
    id: "google-pmax",
    channel: "Google PMax",
    spend: 4200,
    platformReported: 21800,
    ga4: 11400,
    shopifyFirstClick: 8900,
    shopifyLastClick: 14200,
    postPurchaseSurvey: 6200,
    blendedTruth: 9400,
    blendedRoas: 2.24,
    contributionMargin: 1640,
    confidence: "Medium",
    flag: "double_count_risk",
    notes:
      "PMax revenue overlaps with branded search and shopping. Platform reporting overstates incremental value. Treat as a fulfillment channel for warm demand.",
  },
  {
    id: "tiktok-ads",
    channel: "TikTok Ads",
    spend: 3200,
    platformReported: 14800,
    ga4: 4200,
    shopifyFirstClick: 6800,
    shopifyLastClick: 3100,
    postPurchaseSurvey: 9400,
    blendedTruth: 8200,
    blendedRoas: 2.56,
    contributionMargin: 1840,
    confidence: "Medium",
    flag: "view_through_dependent",
    notes:
      "Click-based attribution understates TikTok. Post-purchase survey suggests ~28% of new customers report TikTok as primary discovery source.",
  },
  {
    id: "klaviyo-email",
    channel: "Klaviyo Email",
    spend: 480,
    platformReported: 18400,
    ga4: 17200,
    shopifyFirstClick: 4200,
    shopifyLastClick: 16800,
    postPurchaseSurvey: 2400,
    blendedTruth: 6800,
    blendedRoas: 14.17,
    contributionMargin: 4980,
    confidence: "Low",
    flag: "double_count_risk",
    notes:
      "Email reporting overstates revenue because it captures repeat customers who would have purchased anyway. Use Shopify Blended, not last-click.",
  },
  {
    id: "organic-search",
    channel: "Organic Search",
    spend: 0,
    platformReported: 0,
    ga4: 19400,
    shopifyFirstClick: 14200,
    shopifyLastClick: 21800,
    postPurchaseSurvey: 8400,
    blendedTruth: 12800,
    blendedRoas: 0,
    contributionMargin: 8960,
    confidence: "Medium",
    notes:
      "Organic intercepts intent generated by paid channels. Survey shows ~22% of organic-attributed customers were influenced by paid social or email.",
  },
  {
    id: "direct",
    channel: "Direct",
    spend: 0,
    platformReported: 0,
    ga4: 12200,
    shopifyFirstClick: 4800,
    shopifyLastClick: 14800,
    postPurchaseSurvey: 2200,
    blendedTruth: 6200,
    blendedRoas: 0,
    contributionMargin: 4340,
    confidence: "Low",
    flag: "uplift_unconfirmed",
    notes:
      "Most direct revenue is repeat customers. Survey confirms paid social as primary discovery for many of these orders.",
  },
]

export const attributionDeltas = {
  metaPlatformVsBlended: 24400, // overstatement
  emailLastClickVsBlended: 10000,
  pmaxOverstatement: 12400,
}
