import { ActionableRow } from "./types"

export const actionableData: ActionableRow[] = [
  {
    id: "display-prospecting",
    name: "Display Prospecting",
    level: "Campaign",
    status: "critical",
    priority: 1,
    impact: "high",
    category: "Spend",
    delivery: "Active",
    spend: "$450/day",
    spendTrend: "stable",
    revenue: "$540/day",
    revenueTrend: "down",
    roas: "1.2x",
    roasTarget: "2.0x",
    cpa: "$72",
    cpaTarget: "$45",
    reason: "CPA 60% above target for 10+ days",
    recommendedAction: "Review pause recommendation",
    confidence: 91,
    recentTrend: [1.8, 1.6, 1.5, 1.4, 1.3, 1.25, 1.2],
    expectedImpact: "Protect $1,200/week margin",
    budget: "$450/day",
    attributionWindow: "7-day click",
    impressions: "248,300",
    reach: "187,000",
    frequency: "1.33",
    cpm: "$12.69",
    ctr: "1.12%",
    linkClicks: "2,780",
    cpc: "$1.13",
    landingPageViews: "2,210",
    contentViews: "1,180",
    addsToCart: "156",
    initiateCheckouts: "71",
    purchases: "44",
    aov: "$85.91",
    thruPlays: "—",
    videoP25: "—",
    videoP50: "—",
    videoP75: "—",
    videoP95: "—",
    approvedAction: {
      type: "pause",
      platform: "meta",
      objectType: "campaign",
      objectName: "Display Prospecting",
      currentValueLabel: "Active · $450/day",
      proposedValueLabel: "Paused",
      reason:
        "CPA has held 60% above target for 10+ days while ROAS continues to soften. Pausing protects the weekly margin run-rate.",
      evidence: [
        { label: "CPA", value: "$72", comparison: "vs target $45", trend: "negative" },
        { label: "ROAS", value: "1.2x", comparison: "vs target 2.0x", trend: "negative" },
        { label: "Spend", value: "$450/day", comparison: "stable", trend: "neutral" },
        { label: "Confidence", value: "91%", comparison: "high", trend: "positive" },
      ],
      riskWatchout:
        "Reach may drop in upper-funnel after pause. Watch top-of-funnel reach for 7 days and re-enable if branded search softens more than 10%.",
      confidence: 91,
      hints: { parentChildHierarchy: true },
    },
  },
  {
    id: "broad-18-24",
    name: "Broad Audience 18-24",
    level: "Ad Set",
    status: "critical",
    priority: 2,
    impact: "medium",
    category: "Spend",
    delivery: "Active",
    spend: "$310/5 days",
    spendTrend: "up",
    revenue: "$496",
    revenueTrend: "down",
    roas: "1.6x",
    roasTarget: "2.5x",
    cpa: "$58",
    cpaTarget: "$45",
    reason: "CPA 29% above target, ROAS recovery has not materialized",
    recommendedAction: "Review pause recommendation",
    confidence: 87,
    recentTrend: [2.1, 1.9, 1.8, 1.7, 1.6, 1.6, 1.6],
    expectedImpact: "+$180/week margin if reallocated",
    budget: "$60/day",
    attributionWindow: "7-day click",
    impressions: "89,400",
    reach: "71,200",
    frequency: "1.26",
    cpm: "$14.20",
    ctr: "1.05%",
    linkClicks: "938",
    cpc: "$1.35",
    landingPageViews: "720",
    contentViews: "410",
    addsToCart: "52",
    initiateCheckouts: "19",
    purchases: "9",
    aov: "$55.11",
    approvedAction: {
      type: "pause",
      platform: "meta",
      objectType: "ad_set",
      objectName: "Broad Audience 18-24",
      currentValueLabel: "Active · $60/day",
      proposedValueLabel: "Paused",
      reason:
        "CPA is 29% above target and ROAS has not recovered after 5 days of stable spend. Pausing this ad set frees budget for higher-performing siblings.",
      evidence: [
        { label: "CPA", value: "$58", comparison: "vs target $45", trend: "negative" },
        { label: "ROAS", value: "1.6x", comparison: "vs target 2.5x", trend: "negative" },
        { label: "Spend", value: "$310", comparison: "over 5 days", trend: "neutral" },
        { label: "Confidence", value: "87%", comparison: "high", trend: "positive" },
      ],
      riskWatchout:
        "Sibling ad sets may absorb learning-phase resets. Watch the parent campaign's blended CPA for 48 hours after pause.",
      confidence: 87,
      hints: { parentChildHierarchy: true },
    },
  },
  {
    id: "tiktok-ugc",
    name: "TikTok UGC Campaign",
    level: "Campaign",
    status: "opportunity",
    priority: 3,
    impact: "high",
    category: "Spend",
    delivery: "Active",
    spend: "$220/day",
    spendTrend: "stable",
    revenue: "$880/day",
    revenueTrend: "up",
    roas: "4.0x",
    roasTarget: "2.5x",
    cpa: "$18",
    cpaTarget: "$30",
    reason: "Exceptional ROAS with low CPA, strong scaling potential",
    recommendedAction: "Review budget increase",
    confidence: 95,
    recentTrend: [3.2, 3.4, 3.6, 3.7, 3.8, 3.9, 4.0],
    expectedImpact: "+$2,400/week revenue (modeled)",
    budget: "$220/day",
    attributionWindow: "7-day click",
    impressions: "412,800",
    reach: "312,500",
    frequency: "1.32",
    cpm: "$5.33",
    ctr: "2.41%",
    linkClicks: "9,950",
    cpc: "$0.22",
    landingPageViews: "8,720",
    contentViews: "5,300",
    addsToCart: "940",
    initiateCheckouts: "480",
    purchases: "122",
    aov: "$50.49",
    thruPlays: "28,400",
    videoP25: "88,200",
    videoP50: "64,300",
    videoP75: "41,100",
    videoP95: "22,800",
  },
  {
    id: "summer-sale",
    name: "Summer Sale",
    level: "Campaign",
    status: "opportunity",
    priority: 4,
    impact: "medium",
    category: "Spend",
    delivery: "Active",
    spend: "$420/day",
    spendTrend: "stable",
    revenue: "$1,344/day",
    revenueTrend: "up",
    roas: "3.2x",
    roasTarget: "2.5x",
    cpa: "$41",
    cpaTarget: "$50",
    reason: "ROAS above target for 7 days with stable spend",
    recommendedAction: "Review budget increase",
    confidence: 92,
    recentTrend: [2.8, 2.9, 3.0, 3.1, 3.0, 3.2, 3.2],
    expectedImpact: "+$900/week margin (modeled)",
    budget: "$420/day",
    attributionWindow: "7-day click",
    impressions: "318,200",
    reach: "254,600",
    frequency: "1.25",
    cpm: "$9.24",
    ctr: "1.65%",
    linkClicks: "5,250",
    cpc: "$0.56",
    landingPageViews: "4,460",
    contentViews: "2,920",
    addsToCart: "510",
    initiateCheckouts: "240",
    purchases: "71",
    aov: "$94.52",
    decision:
      "Increased Summer Sale budget from $420/day to $500/day manually in Meta on Apr 17.",
    decisionDate: "Apr 17",
    expectedOutcome: "Maintain CPA below $50 and increase contribution margin.",
    guardrailMetric: "CPA must stay below $50 for 7 days; ROAS must hold above 2.5x.",
    outcomeReviewDate: "Apr 24",
    actualResult:
      "Revenue increased $2,100 over 7 days; contribution margin increased $740. CPA stayed below target.",
    outcomeStatus: "Positive outcome",
    approvedAction: {
      type: "increase_budget",
      platform: "meta",
      objectType: "campaign",
      objectName: "Summer Sale",
      currentValueLabel: "$420/day",
      proposedValueLabel: "$500/day",
      budget: { current: 420, proposed: 500, unit: "daily", currency: "USD" },
      reason:
        "ROAS has held above target for 7 consecutive days and CPA is 18% below target — the campaign appears to have headroom before saturation.",
      evidence: [
        { label: "ROAS", value: "3.2x", comparison: "vs target 2.5x", trend: "positive" },
        { label: "CPA", value: "$41", comparison: "vs target $50", trend: "positive" },
        { label: "Revenue WoW", value: "+18%", comparison: "stable spend", trend: "positive" },
        { label: "Confidence", value: "92%", comparison: "high", trend: "positive" },
      ],
      riskWatchout:
        "If reviewed, watch CPA. Roll back if CPA rises above $50 for 2 consecutive days after the change.",
      confidence: 92,
      hints: {
        parentChildHierarchy: true,
        positiveContributionMargin: true,
        recentRevenue: true,
      },
    },
    children: [
      {
        id: "summer-sale-interest",
        name: "Interest Targeting - Fashion",
        level: "Ad Set",
        status: "opportunity",
        priority: 4,
        impact: "medium",
        delivery: "Active",
        spend: "$180/day",
        spendTrend: "stable",
        revenue: "$612/day",
        revenueTrend: "up",
        roas: "3.4x",
        roasTarget: "2.5x",
        cpa: "$38",
        cpaTarget: "$50",
        reason: "Strong performer with room to scale",
        recommendedAction: "Review budget increase",
        confidence: 88,
        recentTrend: [3.1, 3.2, 3.3, 3.4, 3.3, 3.4, 3.4],
        budget: "$180/day",
        attributionWindow: "7-day click",
        impressions: "142,900",
        reach: "118,200",
        frequency: "1.21",
        cpm: "$8.82",
        ctr: "1.78%",
        linkClicks: "2,540",
        cpc: "$0.50",
        landingPageViews: "2,180",
        contentViews: "1,420",
        addsToCart: "240",
        initiateCheckouts: "110",
        purchases: "33",
        aov: "$130.36",
        approvedAction: {
          type: "increase_budget",
          platform: "meta",
          objectType: "ad_set",
          objectName: "Interest Targeting - Fashion",
          currentValueLabel: "$180/day",
          proposedValueLabel: "$210/day",
          budget: { current: 180, proposed: 210, unit: "daily", currency: "USD" },
          reason:
            "ROAS 36% above target with stable CTR — small step-up keeps the change inside the +20% beta cap.",
          evidence: [
            { label: "ROAS", value: "3.4x", comparison: "vs target 2.5x", trend: "positive" },
            { label: "CPA", value: "$38", comparison: "vs target $50", trend: "positive" },
            { label: "Confidence", value: "88%", comparison: "high", trend: "positive" },
          ],
          riskWatchout:
            "Step-up keeps the parent campaign inside its shared budget. Watch sibling ad sets for unintended re-balancing in the first 48 hours.",
          confidence: 88,
          hints: { sharedBudget: true, parentChildHierarchy: true },
        },
      },
      {
        id: "summer-sale-lookalike",
        name: "Lookalike - Purchasers",
        level: "Ad Set",
        status: "healthy",
        priority: 5,
        impact: "low",
        delivery: "Active",
        spend: "$240/day",
        spendTrend: "stable",
        revenue: "$732/day",
        revenueTrend: "stable",
        roas: "3.05x",
        roasTarget: "2.5x",
        cpa: "$44",
        cpaTarget: "$50",
        reason: "Performance remains above target",
        recommendedAction: "No action needed",
        confidence: 85,
        recentTrend: [3.0, 3.0, 3.1, 3.0, 3.0, 3.05, 3.05],
        budget: "$240/day",
        attributionWindow: "7-day click",
        impressions: "168,300",
        reach: "132,800",
        frequency: "1.27",
        cpm: "$9.98",
        ctr: "1.40%",
        linkClicks: "2,360",
        cpc: "$0.71",
        landingPageViews: "1,980",
        contentViews: "1,290",
        addsToCart: "218",
        initiateCheckouts: "96",
        purchases: "38",
        aov: "$138.10",
      },
    ],
  },
  {
    id: "google-search",
    name: "Google Search - Brand",
    level: "Campaign",
    status: "watch",
    priority: 5,
    impact: "medium",
    category: "Spend",
    delivery: "Active",
    spend: "$890/day",
    spendTrend: "up",
    revenue: "$2,403/day",
    revenueTrend: "down",
    roas: "2.7x",
    roasTarget: "3.0x",
    cpa: "$32",
    cpaTarget: "$30",
    reason: "Search costs rising while efficiency softens (-9% ROAS)",
    recommendedAction: "Review budget decrease",
    confidence: 72,
    recentTrend: [3.0, 2.95, 2.9, 2.85, 2.8, 2.75, 2.7],
    expectedImpact: "Up to $400/week at risk if trend continues",
    budget: "$890/day",
    attributionWindow: "Data-driven",
    impressions: "124,500",
    reach: "98,200",
    frequency: "1.27",
    cpm: "$50.04",
    ctr: "6.85%",
    linkClicks: "8,530",
    cpc: "$0.73",
    landingPageViews: "7,920",
    contentViews: "5,460",
    addsToCart: "770",
    initiateCheckouts: "380",
    purchases: "195",
    aov: "$86.31",
    approvedAction: {
      type: "decrease_budget",
      platform: "google",
      objectType: "campaign",
      objectName: "Google Search - Brand",
      currentValueLabel: "$890/day",
      proposedValueLabel: "$720/day",
      budget: { current: 890, proposed: 720, unit: "daily", currency: "USD" },
      reason:
        "CPC has risen 11% week over week while ROAS has softened 9%. A precautionary 19% step-down stays inside the -30% beta cap and protects margin while the trend resolves.",
      evidence: [
        { label: "CPC", value: "+11%", comparison: "week over week", trend: "negative" },
        { label: "ROAS", value: "2.7x", comparison: "vs target 3.0x", trend: "negative" },
        { label: "Confidence", value: "72%", comparison: "moderate", trend: "neutral" },
      ],
      riskWatchout:
        "Branded search may lose impression share. Watch impression share daily; revert if it drops more than 8 points.",
      confidence: 72,
      hints: { recentRevenue: true, positiveContributionMargin: true },
    },
  },
  {
    id: "retargeting-30d",
    name: "Retargeting - Purchasers 30D",
    level: "Ad Set",
    status: "healthy",
    priority: 5,
    impact: "low",
    delivery: "Active",
    spend: "$180/day",
    spendTrend: "stable",
    revenue: "$612/day",
    revenueTrend: "stable",
    roas: "3.4x",
    roasTarget: "2.5x",
    cpa: "$29",
    cpaTarget: "$35",
    reason: "Performance remains above target",
    recommendedAction: "No action needed",
    confidence: 94,
    recentTrend: [3.3, 3.35, 3.4, 3.38, 3.4, 3.42, 3.4],
    budget: "$180/day",
    attributionWindow: "7-day click",
    impressions: "38,400",
    reach: "14,200",
    frequency: "2.70",
    cpm: "$32.81",
    ctr: "4.20%",
    linkClicks: "1,613",
    cpc: "$0.78",
    landingPageViews: "1,510",
    contentViews: "1,230",
    addsToCart: "290",
    initiateCheckouts: "158",
    purchases: "65",
    aov: "$65.82",
  },
  {
    id: "youtube-awareness",
    name: "YouTube Awareness",
    level: "Campaign",
    status: "watch",
    priority: 5,
    impact: "low",
    delivery: "Active",
    spend: "$320/day",
    spendTrend: "stable",
    revenue: "$736/day",
    revenueTrend: "stable",
    roas: "2.3x",
    roasTarget: "2.5x",
    cpa: "$41",
    cpaTarget: "$40",
    reason: "Slightly below ROAS target, monitoring for trend",
    recommendedAction: "Monitor",
    confidence: 65,
    recentTrend: [2.4, 2.35, 2.3, 2.32, 2.3, 2.28, 2.3],
    budget: "$320/day",
    attributionWindow: "7-day click",
    impressions: "524,800",
    reach: "412,000",
    frequency: "1.27",
    cpm: "$4.27",
    ctr: "0.42%",
    linkClicks: "2,200",
    cpc: "$1.02",
    landingPageViews: "1,840",
    contentViews: "1,060",
    addsToCart: "142",
    initiateCheckouts: "56",
    purchases: "22",
    aov: "$33.45",
    thruPlays: "142,800",
    videoP25: "380,200",
    videoP50: "245,100",
    videoP75: "132,400",
    videoP95: "72,800",
  },
  {
    id: "pinterest-seasonal",
    name: "Pinterest Seasonal",
    level: "Campaign",
    status: "healthy",
    priority: 5,
    impact: "low",
    delivery: "Active",
    spend: "$150/day",
    spendTrend: "stable",
    revenue: "$420/day",
    revenueTrend: "up",
    roas: "2.8x",
    roasTarget: "2.5x",
    cpa: "$35",
    cpaTarget: "$40",
    reason: "Consistent above-target performance",
    recommendedAction: "No action needed",
    confidence: 88,
    recentTrend: [2.6, 2.65, 2.7, 2.72, 2.75, 2.78, 2.8],
    budget: "$150/day",
    attributionWindow: "7-day click",
    impressions: "92,400",
    reach: "71,200",
    frequency: "1.30",
    cpm: "$11.36",
    ctr: "1.26%",
    linkClicks: "1,168",
    cpc: "$0.90",
    landingPageViews: "980",
    contentViews: "620",
    addsToCart: "92",
    initiateCheckouts: "44",
    purchases: "12",
    aov: "$35.00",
  },
  // Phase 2 — Creative
  {
    id: "creative-carousel-fatigue",
    name: "Carousel Product Grid",
    level: "Creative",
    status: "watch",
    priority: 2,
    impact: "medium",
    category: "Creative",
    delivery: "Active",
    spend: "$2,840",
    spendTrend: "stable",
    revenue: "$7,820",
    revenueTrend: "down",
    roas: "2.75x",
    roasTarget: "3.0x",
    cpa: "$41.20",
    cpaTarget: "$35",
    reason: "CTR down 25% over 14 days · frequency above 4.0",
    recommendedAction: "Review creative refresh",
    confidence: 84,
    recentTrend: [3.4, 3.25, 3.1, 2.98, 2.88, 2.82, 2.75],
    expectedImpact: "Up to $1,200/week margin if refreshed",
    budget: "—",
    attributionWindow: "7-day click",
    impressions: "142,800",
    reach: "102,100",
    frequency: "1.40",
    cpm: "$19.89",
    ctr: "0.85%",
    linkClicks: "1,213",
    cpc: "$2.34",
    landingPageViews: "1,020",
    contentViews: "710",
    addsToCart: "98",
    initiateCheckouts: "42",
    purchases: "69",
    aov: "$113.33",
  },
  // Phase 2 — Product
  {
    id: "product-trail-runner-refunds",
    name: "Trail Runner",
    level: "Product",
    status: "critical",
    priority: 2,
    impact: "high",
    category: "Product",
    delivery: "Active",
    spend: "$4,720",
    spendTrend: "stable",
    revenue: "$19,200",
    revenueTrend: "stable",
    roas: "—",
    cpa: "—",
    reason: "Refund rate 8.4% — 3x store average; margin at risk",
    recommendedAction: "Review refund issue",
    confidence: 89,
    recentTrend: [6.2, 6.8, 7.1, 7.4, 7.8, 8.1, 8.4],
    expectedImpact: "Up to $1,400/week margin if refunds normalize",
  },
  // Phase 2 — Attribution
  {
    id: "attribution-pmax-overstatement",
    name: "Google PMax",
    level: "Channel",
    status: "watch",
    priority: 3,
    impact: "medium",
    category: "Attribution",
    delivery: "Active",
    spend: "$4,200",
    spendTrend: "stable",
    revenue: "$9,400",
    revenueTrend: "stable",
    roas: "2.24x",
    roasTarget: "2.5x",
    cpa: "—",
    reason: "Platform reports 2.3× the Shopify Blended view — double-count risk",
    recommendedAction: "Review attribution treatment",
    confidence: 78,
    recentTrend: [3.1, 2.95, 2.8, 2.6, 2.45, 2.32, 2.24],
    expectedImpact: "Up to $1,200/week reallocation opportunity",
    budget: "—",
    attributionWindow: "Data-driven",
    impressions: "1,210,400",
    reach: "920,400",
    frequency: "1.32",
    cpm: "$3.47",
    ctr: "0.61%",
    linkClicks: "7,380",
    cpc: "$0.57",
    landingPageViews: "6,440",
    contentViews: "4,220",
    addsToCart: "580",
    initiateCheckouts: "290",
    purchases: "—",
    aov: "—",
  },
  // Phase 2 — Cohort
  {
    id: "cohort-pmax-payback",
    name: "Recent PMax cohort",
    level: "Cohort",
    status: "watch",
    priority: 3,
    impact: "medium",
    category: "Cohort",
    delivery: "Active",
    spend: "—",
    spendTrend: "stable",
    revenue: "—",
    revenueTrend: "stable",
    roas: "—",
    cpa: "—",
    reason: "Payback 78 days vs 45-day target — slow recovery",
    recommendedAction: "Review acquisition mix",
    confidence: 76,
    recentTrend: [50, 56, 62, 68, 72, 76, 78],
    expectedImpact: "Improves working capital flexibility",
  },
  // Phase 3B — Inventory
  {
    id: "inventory-cotton-tee-stockout",
    name: "Premium Cotton Tee",
    level: "Inventory",
    status: "critical",
    priority: 1,
    impact: "high",
    category: "Inventory",
    delivery: "Active",
    spend: "$9,940",
    spendTrend: "stable",
    revenue: "$41,200",
    revenueTrend: "stable",
    roas: "—",
    cpa: "—",
    reason: "11 days of inventory left at current sales velocity (38/day)",
    recommendedAction: "Review reorder timing and ad spend allocation",
    confidence: 91,
    recentTrend: [22, 19, 17, 15, 14, 12, 11],
    expectedImpact: "Up to $24,100 revenue at risk if SKU sells out",
  },
  {
    id: "inventory-merino-sock-critical",
    name: "Merino Quarter Sock",
    level: "Inventory",
    status: "critical",
    priority: 2,
    impact: "medium",
    category: "Inventory",
    delivery: "Active",
    spend: "$1,680",
    spendTrend: "stable",
    revenue: "$11,200",
    revenueTrend: "stable",
    roas: "—",
    cpa: "—",
    reason: "8 days of inventory at 24/day velocity — high-margin SKU (45% CM)",
    recommendedAction: "View product",
    confidence: 88,
    recentTrend: [16, 14, 12, 11, 10, 9, 8],
    expectedImpact: "$3,010 contribution margin at risk",
  },
  // Phase 3B — Subscription
  {
    id: "subscription-month2-retention",
    name: "Recent subscription cohort",
    level: "Subscription",
    status: "watch",
    priority: 3,
    impact: "medium",
    category: "Subscription",
    delivery: "Active",
    spend: "—",
    spendTrend: "stable",
    revenue: "—",
    revenueTrend: "down",
    roas: "—",
    cpa: "—",
    reason: "Month-2 retention 79.2% vs 85% target; same-day cancels at 14.8%",
    recommendedAction: "Inspect cancel reasons",
    confidence: 84,
    recentTrend: [88, 86, 84, 82, 81, 80, 79],
    expectedImpact: "Retention recovery worth ~$8,400/month in renewal revenue",
  },
]

/**
 * Aggregate counts powering the Action Center's filter chips and the
 * Insights panel header. Three buckets, one-to-one with the three
 * Insights columns:
 *   - attention: critical + watch rows ("Attention Needed" column)
 *   - scale:     opportunity rows       ("Opportunities" column)
 *   - healthy:   healthy rows           ("Key Changes" column — these are
 *                the campaigns we want to keep an eye on so they don't
 *                quietly slip out of healthy state)
 *
 * `estimatedImpact` is the combined dollar value of the savings and
 * scaling opportunities, surfaced in the Insights header instead of
 * pretending to be a fourth filter chip.
 */
export const actionSummary = {
  attention: 5,
  scale: 2,
  healthy: 3,
  estimatedSavings: "$1,420/week",
  estimatedGrowth: "$2,400/week",
  estimatedImpact: "$3,820/wk",
}
